package com.github.stifred.aoc2025.day07

import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.Test

class TachyonManifoldTest {
  @Test
  fun `test input`() {
    val input = """
      .......S.......
      ...............
      .......^.......
      ...............
      ......^.^......
      ...............
      .....^.^.^.....
      ...............
      ....^.^...^....
      ...............
      ...^.^...^.^...
      ...............
      ..^...^.....^..
      ...............
      .^.^.^.^.^...^.
      ...............
    """.trimIndent()
    val manifold = input.asTachyonManifold()

    assertEquals(21 to 40L, manifold.sendQuantumBeamAndCountTimelines())
  }
}
